### ISSUE TITLE
Building binary with Kerberos support in container

### ISSUE THREAD

**Issue by KaluTheKova** [beltran/gohive#115] opened 2020-10-05 13:02 UTC
Hello again. I'm trying to build my program in a multistage container build.
I'm using `golang:1.15.2-buster` as builder image.

pip list shows that gssapi is installed.
```Step 18/28 : RUN pip list
 ---> Running in cedd3c0e325d
Package       Version
------------- -------
asn1crypto    0.24.0
configparser  3.5.0b2
cryptography  2.6.1
decorator     4.4.2
entrypoints   0.3
enum34        1.1.6
gssapi        1.6.2
ipaddress     1.0.17
keyring       17.1.1
keyrings.alt  3.1.1
mercurial     4.8.2
pip           18.1
pycrypto      2.6.1
PyGObject     3.30.4
pyxdg         0.25
SecretStorage 2.3.1
setuptools    40.8.0
six           1.12.0
wheel         0.32.3
```
I get the following errors:
```
Step 19/28 : RUN go get -tags kerberos github.com/beltran/gohive
 ---> Running in b8866152dcec
go: github.com/beltran/gohive upgrade => v1.2.0
go: downloading github.com/beltran/gohive v1.2.0
# github.com/beltran/gosasl
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200513032552-d3700baa7593/gssapi.go:62:16: undefined: gssapi.Name
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200513032552-d3700baa7593/gssapi.go:181:2: undefined: gssapi.Options
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200513032552-d3700baa7593/gssapi.go:183:2: undefined: gssapi.Lib
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200513032552-d3700baa7593/gssapi.go:187:18: undefined: gssapi.CredId
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200513032552-d3700baa7593/gssapi.go:190:18: undefined: gssapi.CtxId
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200513032552-d3700baa7593/gssapi.go:198:20: undefined: gssapi.GSS_C_INTEG_FLAG
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200513032552-d3700baa7593/gssapi.go:198:54: undefined: gssapi.GSS_C_MUTUAL_FLAG
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200513032552-d3700baa7593/gssapi.go:198:89: undefined: gssapi.GSS_C_SEQUENCE_FLAG
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200513032552-d3700baa7593/gssapi.go:198:126: undefined: gssapi.GSS_C_CONF_FLAG
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200513032552-d3700baa7593/gssapi.go:326:44: undefined: gssapi.Name
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200513032552-d3700baa7593/gssapi.go:198:126: too many errors
```

Am I missing something important, am I running a wrong version of GoHive or is there some other problem?
To me it seems that gssapi cannot be found despite it being installed.

**Comment by beltran** [comment] 2020-10-06 00:31
`pip list` would indicate the gssapi python package is installed (https://pypi.org/project/gssapi/). But the gssapi c libraries could not be installed. If you can share the Dockerfile I wouldn't mind taking a closer a look.

**Comment by beltran** [comment] 2020-10-06 00:43
Looks like the problem is with the go gasspi dependency, I'm not sure if the error is really indicating the c gssapi files are not installed, if you can get the whole list of errors that would be useful as well (since the error output ends with `gssapi.go:198:126: too many errors`). You can aslo try `go get github.com/beltran/gssapi` and see the errors with that command.

**Comment by KaluTheKova** [comment] 2020-10-07 12:24
Running ```go get github.com/beltran/gssapi``` causes no errors.
Running ```go get -tags kerberos github.com/beltran/gssapi``` causes no errors.
Running ``` go get github.com/beltran/gosasl``` outputs: 
```
go: github.com/beltran/gosasl upgrade => v0.0.0-20200715011608-d5475aebb293
go: downloading github.com/beltran/gosasl v0.0.0-20200715011608-d5475aebb293
```
And is successful.

Running ```go get -tags kerberos github.com/beltran/gosasl``` outputs:
```
go: github.com/beltran/gosasl upgrade => v0.0.0-20200715011608-d5475aebb293
go: downloading github.com/beltran/gosasl v0.0.0-20200715011608-d5475aebb293
# github.com/beltran/gosasl
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200715011608-d5475aebb293/gssapi.go:62:16: undefined: gssapi.Name
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200715011608-d5475aebb293/gssapi.go:181:2: undefined: gssapi.Options
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200715011608-d5475aebb293/gssapi.go:183:2: undefined: gssapi.Lib
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200715011608-d5475aebb293/gssapi.go:187:18: undefined: gssapi.CredId
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200715011608-d5475aebb293/gssapi.go:190:18: undefined: gssapi.CtxId
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200715011608-d5475aebb293/gssapi.go:198:20: undefined: gssapi.GSS_C_INTEG_FLAG
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200715011608-d5475aebb293/gssapi.go:198:54: undefined: gssapi.GSS_C_MUTUAL_FLAG
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200715011608-d5475aebb293/gssapi.go:198:89: undefined: gssapi.GSS_C_SEQUENCE_FLAG
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200715011608-d5475aebb293/gssapi.go:198:126: undefined: gssapi.GSS_C_CONF_FLAG
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200715011608-d5475aebb293/gssapi.go:326:44: undefined: gssapi.Name
/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200715011608-d5475aebb293/gssapi.go:198:126: too many errors
```
I honestly have no idea how I could make go show more errors during package install :(.

**Comment by KaluTheKova** [comment] 2020-10-07 12:25
And here is the dockerfile I'm using.
```
FROM golang:1.15.2-buster AS builder

# Set necessary environmet variables needed for our image
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \ 
    GOPROXY="SANITIZED"

# Move to working directory /build
WORKDIR /build

# Copy and download dependency using go mod
COPY go.mod .
COPY go.sum .
RUN go mod download

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get install python-pip libkrb5-dev -y
RUN pip install gssapi
RUN pip list

RUN go install -tags kerberos "github.com/beltran/gohive"

# Copy the code into the container
COPY . .

# Build the binary
RUN go build -o main .

# Move to /bin for the resulting binary file
WORKDIR /bin

# Copy binary from build to main folder
RUN cp /build/main .

COPY . .

# Start from scratch
FROM scratch

# Copy the binary
COPY --from=builder /bin/main /

# Add user
USER 1000

# Command to run
ENTRYPOINT [ "/main" ]
```

**Comment by beltran** [comment] 2020-10-07 14:28
I'm not sure why but I believe this is caused by setting `CGO_ENABLED=0`, it works I think with `CGO_ENABLED=1`, do you need to set this to zero?

**Comment by KaluTheKova** [comment] 2020-10-09 13:17
You are correct, that solves it! Thank you very much.

**Comment by beltran** [comment] 2020-10-09 14:21
Happy to help, closing this for now

**Closed by beltran** 2020-10-09 14:21 UTC
