### ISSUE TITLE
panic: gosasl may have been installed without kerberos support - error with "go build -tags kerberos"

### ISSUE THREAD

**Issue by KaluTheKova** [beltran/gohive#119] opened 2020-10-21 08:23 UTC
Hello once again :). I finally got back to this and face another problem.

Despite having go build -tags kerberos in Dockerfile, I get:
```
Panic: gosasl may have been installed without kerberos support please reinstall with `go get` using the flags `build kerberos`. Alternatively if `go run` is being ran it should be ran with `go run -tags kerberos ...` and the binary should have been build with `go build -tags kerberos ...`.

goroutine 1 [running]:
github.com/beltran/gosasl.NewGSSAPIMechanism(...)
        /go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200513032552-d3700baa7593/no_gssapi.go:14
github.com/beltran/gohive.NewTSaslTransport(0x8c7440, 0xc0000a0240, 0xc00001e00a, 0x24, 0x842f8c, 0x6, 0xc0001a3290, 0x4bf785, 0xc00007c120, 0x2)
        /go/pkg/mod/github.com/beltran/gohive@v1.1.0/sasl_transport.go:48 +0x4bb
github.com/beltran/gohive.innerConnect(0xc00001e00a, 0x24, 0x1f49, 0xc00001a9c8, 0x8, 0xc0001b6000, 0xc00011e540, 0x40, 0x40)
        /go/pkg/mod/github.com/beltran/gohive@v1.1.0/hive.go:246 +0xda8
github.com/beltran/gohive.Connect(...)
        /go/pkg/mod/github.com/beltran/gohive@v1.1.0/hive.go:119
SANITIZED/internal/hive.New(0xc00001e00a, 0x24, 0x1f49, 0xc00001a9c8, 0x8, 0xc00001c0ce, 0x4, 0xc00001c10e, 0x4, 0xc00001c00e, ...)
        /build/internal/hive/client.go:61 +0x1f9
main.createClients(0xc00001e00a, 0x24, 0x1f49, 0xc00001a9c8, 0x8, 0xc00001c0ce, 0x4, 0xc00001c10e, 0x4, 0xc00001c00e, ...)
        /build/main.go:234 +0x58
main.main()
        /build/main.go:78 +0x46d
```

I have tried running go get gosasl and go get gohive in Dockerfile with -tags kerberos.
Using ENTRYPOINT ["/main"] or CMD  in Dockerfile outputs the error above.

Here is the Dockerfile:
```
FROM SANITIZED/golang:1.15.2-buster AS builder

# Set necessary environmet variables needed for our image
ENV GO111MODULE=on \
    CGO_ENABLED=1 \
    GOOS=linux \
    GOARCH=amd64 \ 
    GOPROXY="SANITIZED"

# Move to working directory /build
WORKDIR /build

RUN sed -i 'SANITIZED' /etc/apt/sources.list
RUN sed -i 'SANITIZED' /etc/apt/sources.list

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

RUN apt-get install python-pip libkrb5-dev -y python-gssapi libgssapi-krb5-2
RUN pip install gssapi
RUN pip list

RUN go get -tags kerberos "github.com/beltran/gosasl"
RUN go get -tags kerberos "github.com/beltran/gohive"

# Copy and download dependency using go mod
COPY go.mod .
COPY go.sum .
RUN go mod download

# Copy the code into the container
COPY . .

# Build binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags kerberos -tags netgo -a -ldflags '-w -extldflags "-static"' -o main .

# Move to /bin for the resulting binary file
WORKDIR /bin

# Copy binary from build to main folder
RUN cp /build/main .

COPY . .

# Start from scratch
FROM scratch

# Copy the binary
COPY --from=builder /bin/main /

# Add user
USER 1000

# Command to run
ENTRYPOINT [ "/main"]
```

**Comment by beltran** [comment] 2020-10-21 12:45
Hello, I think this line may be guilty `RUN go get -tags kerberos "github.com/beltran/gosasl"`, can you give it a try removing it?

**Comment by KaluTheKova** [comment] 2020-10-21 18:31
I have removed ```RUN go get -tags kerberos "github.com/beltran/gosasl"```, but still get the same error: ```panic: gosasl may have been installed without kerberos support...```.

**Comment by beltran** [comment] 2020-10-21 19:30
I can't reproduce but this works fine (doesn't give me an error) with the following:

Dockerfile is:

```
# Set necessary environmet variables needed for our image
ENV GO111MODULE=on \
    CGO_ENABLED=1 \
    GOOS=linux \
    GOARCH=amd64

# Move to working directory /build
WORKDIR /build

#RUN sed -i 'SANITIZED' /etc/apt/sources.list
#RUN sed -i 'SANITIZED' /etc/apt/sources.list

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

RUN apt-get install python-pip libkrb5-dev -y python-gssapi libgssapi-krb5-2
RUN pip install gssapi
RUN pip list

# RUN go get -tags kerberos "github.com/beltran/gosasl"
RUN go get -tags kerberos "github.com/beltran/gohive"

# Move to /bin for the resulting binary file
WORKDIR /go/pkg/mod/github.com/beltran/gohive@v1.2.0

RUN cd /go/pkg/mod/github.com/beltran/gohive@v1.2.0 && sed -i 's/hs2.example.com/172.17.0.1/g' example/main.go
```

I build and run it:

```
docker build .
docker run e91422cc9e08 /bin/sh -c 'cd /go/pkg/mod/github.com/beltran/gohive@v1.2.0 && go run -tags kerberos example/main.go'
```

The error I get is different than yours:
```
Bad SASL negotiation status: 3 (GSS initiate failed)
```
which means gohive was installed correctly.


I can't exactly run your Dockerfile because I don't have your `go.mod` and `go.sum`.

**Comment by KaluTheKova** [comment] 2020-10-23 09:15
I can get it to work with "go run -tags kerberos". However, the problem appears when I build the binary with -tags kerberos and try to run the binary through ENTRYPOINT or CMD.

Aaaand here you go, go.mod and go.sum to help you reproduce :).

go.mod
```
module hdfs-writer

go 1.14

require (
	github.com/apache/thrift v0.13.0 // indirect
	github.com/beltran/gohive v1.1.0
	github.com/beltran/gosasl v0.0.0-20200513032552-d3700baa7593 // indirect
	github.com/deckarep/golang-set v1.7.1
	github.com/ilyakaznacheev/cleanenv v1.2.3
	github.com/kelseyhightower/envconfig v1.4.0
	github.com/sirupsen/logrus v1.6.0
	github.com/stretchr/testify v1.3.0
	github.com/t-tomalak/logrus-easy-formatter v0.0.0-20190827215021-c074f06c5816
	gopkg.in/yaml.v2 v2.3.0
)
```

go.sum
```
github.com/BurntSushi/toml v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
github.com/BurntSushi/toml v0.3.1/go.mod h1:xHWCNGjB5oqiDr8zfno3MHue2Ht5sIBksp03qcyfWMU=
github.com/apache/thrift v0.12.0 h1:pODnxUFNcjP9UTLZGTdeh+j16A8lJbRvD3rOtrk/7bs=
github.com/apache/thrift v0.12.0/go.mod h1:cp2SuWMxlEZw2r+iP2GNCdIi4C1qmUzdZFSVb+bacwQ=
github.com/apache/thrift v0.13.0 h1:5hryIiq9gtn+MiLVn0wP37kb/uTeRZgN08WoCsAhIhI=
github.com/apache/thrift v0.13.0/go.mod h1:cp2SuWMxlEZw2r+iP2GNCdIi4C1qmUzdZFSVb+bacwQ=
github.com/beltran/gohive v1.1.0 h1:AoMUCT11vgz9CgIcxHKg68+6C96MM+heWFjbYbVJG54=
github.com/beltran/gohive v1.1.0/go.mod h1:tb+qKRu6ag17EKjuSgLri+cPEA9QCATs62RC7gp9vg0=
github.com/beltran/gosasl v0.0.0-20200326175049-9dfbcb61a4b3 h1:q832ARlau2fGuPSJe3Cuahdf4iS4LdQOYWPINojTSLc=
github.com/beltran/gosasl v0.0.0-20200326175049-9dfbcb61a4b3/go.mod h1:Qx8cW6jkI8riyzmklj80kAIkv+iezFUTBiGU0qHhHes=
github.com/beltran/gosasl v0.0.0-20200513032552-d3700baa7593 h1:+CofSOeu+dXtANvH0VGR0K2dswnEUR6BOcGb3uXxOvk=
github.com/beltran/gosasl v0.0.0-20200513032552-d3700baa7593/go.mod h1:Qx8cW6jkI8riyzmklj80kAIkv+iezFUTBiGU0qHhHes=
github.com/beltran/gssapi v0.0.0-20200324152954-d86554db4bab h1:ayfcn60tXOSYy5zUN1AMSTQo4nJCf7hrdzAVchpPst4=
github.com/beltran/gssapi v0.0.0-20200324152954-d86554db4bab/go.mod h1:GLe4UoSyvJ3cVG+DVtKen5eAiaD8mAJFuV5PT3Eeg9Q=
github.com/davecgh/go-spew v1.1.0 h1:ZDRjVQ15GmhC3fiQ8ni8+OwkZQO4DARzQgrnXU1Liz8=
github.com/davecgh/go-spew v1.1.0/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
github.com/davecgh/go-spew v1.1.1 h1:vj9j/u1bqnvCEfJOwUhtlOARqs3+rkHYY13jYWTU97c=
github.com/davecgh/go-spew v1.1.1/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
github.com/deckarep/golang-set v1.7.1 h1:SCQV0S6gTtp6itiFrTqI+pfmJ4LN85S1YzhDf9rTHJQ=
github.com/deckarep/golang-set v1.7.1/go.mod h1:93vsz/8Wt4joVM7c2AVqh+YRMiUSc14yDtF28KmMOgQ=
github.com/go-zookeeper/zk v1.0.1 h1:LmXNmSnkNsNKai+aDu6sHRr8ZJzIrHJo8z8Z4sm8cT8=
github.com/go-zookeeper/zk v1.0.1/go.mod h1:gpJdHazfkmlg4V0rt0vYeHYJHSL8hHFwV0qOd+HRTJE=
github.com/ilyakaznacheev/cleanenv v1.2.3 h1:EjZD1ATWWHNSGjc+W0LcGuoRBdsJHN3VVQQMB2EIDDQ=
github.com/ilyakaznacheev/cleanenv v1.2.3/go.mod h1:/i3yhzwZ3s7hacNERGFwvlhwXMDcaqwIzmayEhbRplk=
github.com/joho/godotenv v1.3.0 h1:Zjp+RcGpHhGlrMbJzXTrZZPrWj+1vfm90La1wgB6Bhc=
github.com/joho/godotenv v1.3.0/go.mod h1:7hK45KPybAkOC6peb+G5yklZfMxEjkZhHbwpqxOKXbg=
github.com/kelseyhightower/envconfig v1.4.0 h1:Im6hONhd3pLkfDFsbRgu68RDNkGF1r3dvMUtDTo2cv8=
github.com/kelseyhightower/envconfig v1.4.0/go.mod h1:cccZRl6mQpaq41TPp5QxidR+Sa3axMbJDNb//FQX6Gg=
github.com/konsorten/go-windows-terminal-sequences v1.0.1/go.mod h1:T0+1ngSBFLxvqU3pZ+m/2kptfBszLMUkC4ZK/EgS/cQ=
github.com/konsorten/go-windows-terminal-sequences v1.0.3 h1:CE8S1cTafDpPvMhIxNJKvHsGVBgn1xWYf1NbHQhywc8=
github.com/konsorten/go-windows-terminal-sequences v1.0.3/go.mod h1:T0+1ngSBFLxvqU3pZ+m/2kptfBszLMUkC4ZK/EgS/cQ=
github.com/pmezard/go-difflib v1.0.0 h1:4DBwDE0NGyQoBHbLQYPwSUPoCMWR5BEzIk/f1lZbAQM=
github.com/pmezard/go-difflib v1.0.0/go.mod h1:iKH77koFhYxTK1pcRnkKkqfTogsbg7gZNVY4sRDYZ/4=
github.com/sirupsen/logrus v1.4.2/go.mod h1:tLMulIdttU9McNUspp0xgXVQah82FyeX6MwdIuYE2rE=
github.com/sirupsen/logrus v1.6.0 h1:UBcNElsrwanuuMsnGSlYmtmgbb23qDR5dG+6X6Oo89I=
github.com/sirupsen/logrus v1.6.0/go.mod h1:7uNnSEd1DgxDLC74fIahvMZmmYsHGZGEOFrfsX/uA88=
github.com/stretchr/objx v0.1.0 h1:4G4v2dO3VZwixGIRoQ5Lfboy6nUhCyYzaqnIAPPhYs4=
github.com/stretchr/objx v0.1.0/go.mod h1:HFkY916IF+rwdDfMAkV7OtwuqBVzrE8GR6GFx+wExME=
github.com/stretchr/objx v0.1.1/go.mod h1:HFkY916IF+rwdDfMAkV7OtwuqBVzrE8GR6GFx+wExME=
github.com/stretchr/testify v1.2.2/go.mod h1:a8OnRcib4nhh0OaRAV+Yts87kKdq0PP7pXfy6kDkUVs=
github.com/stretchr/testify v1.3.0 h1:TivCn/peBQ7UY8ooIcPgZFpTNSz0Q2U6UrFlUfqbe0Q=
github.com/stretchr/testify v1.3.0/go.mod h1:M5WIy9Dh21IEIfnGCwXGc5bZfKNJtfHm1UVUgZn+9EI=
github.com/t-tomalak/logrus-easy-formatter v0.0.0-20190827215021-c074f06c5816 h1:J6v8awz+me+xeb/cUTotKgceAYouhIB3pjzgRd6IlGk=
github.com/t-tomalak/logrus-easy-formatter v0.0.0-20190827215021-c074f06c5816/go.mod h1:tzym/CEb5jnFI+Q0k4Qq3+LvRF4gO3E2pxS8fHP8jcA=
golang.org/x/sys v0.0.0-20190422165155-953cdadca894 h1:Cz4ceDQGXuKRnVBDTS23GTn/pU5OE2C0WrNTOYK1Uuc=
golang.org/x/sys v0.0.0-20190422165155-953cdadca894/go.mod h1:h1NjWce9XRLGQEsW7wpKNCjG9DtNlClVuFLEZdDNbEs=
gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405 h1:yhCVgyC4o1eVCa2tZl7eS0r+SDo693bJlVdllGtEeKM=
gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405/go.mod h1:Co6ibVJAznAaIkqp8huTwlJQCZ016jof/cbN4VW5Yz0=
gopkg.in/yaml.v2 v2.2.2/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
gopkg.in/yaml.v2 v2.3.0 h1:clyUAQHOM3G0M3f5vQj7LuJrETvjVot3Z5el9nffUtU=
gopkg.in/yaml.v2 v2.3.0/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
olympos.io/encoding/edn v0.0.0-20200308123125-93e3b8dd0e24 h1:sreVOrDp0/ezb0CHKVek/l7YwpxPJqv+jT3izfSphA4=
olympos.io/encoding/edn v0.0.0-20200308123125-93e3b8dd0e24/go.mod h1:oVgVk4OWVDi43qWBEyGhXgYxt7+ED4iYNpTngSLX2Iw=
```

**Comment by beltran** [comment] 2020-10-23 14:20
Hello, I actually also need the code in your home directory, due to the command `COPY . .`. I see you build the binary with `RUN CGO_ENABLED=0 GOOS=linux`, could the `CGO_ENABLED=0` be the issue here like it was at one point before?

I think you are going to have to set `CGO_ENABLED=1` to be able to use gohive because gosasl is calling c code to do the kerberos authentication (which is what cgo is for https://golang.org/cmd/cgo/), do you need to set have it set to `CGO_ENABLED=0`?

**Comment by KaluTheKova** [comment] 2020-11-06 09:01
Helloes. I got it working. 

In this case, go binary needs GSSAPI and kerberos libraries to work as a statically linked binary.

So I check what libraries the binary needs with:
```RUN ldd binary_name```
Output:
```
linux-vdso.so.1 (0x00007ffd5ef26000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2013e73000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2013e6e000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2013cad000)
/lib64/ld-linux-x86-64.so.2 (0x00007f2013e9b000)
```
then copy those libraries (and their required symlinks) into Scratch with:
```
COPY --from=builder /lib64/* /lib64/
COPY --from=builder /lib/* /lib/
COPY --from=builder /usr/lib/* /usr/lib/
```
From here, all the unnecessary libs can be removed or you can figure the exact libs and only copy them during the COPY phase.

**Comment by beltran** [comment] 2020-11-06 09:39
Interesting, hadn't come across this problem yet, thank you for sharing the solution.

**Comment by beltran** [comment] 2020-11-08 15:31
Closing this since the issue seems solved, feel free to reopen if it's not.

**Closed by beltran** 2020-11-08 15:31 UTC
