### ISSUE TITLE
Connecting to locally hosted Hive

### ISSUE THREAD

**Issue by KaluTheKova** [beltran/gohive#94] opened 2020-05-08 13:36 UTC
Hello,

I'm a golang beginner, so please excuse me if this is an issue on my end. 

I'm running Hive locally and want to connect to it from my code.

I installed the package with 'go get github.com/beltran/gohive' and tried to run the example code in my project.

When I run the code, I get this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6525e0]

goroutine 1 [running]:
github.com/apache/thrift/lib/go/thrift.(*TSocket).IsOpen(...)
	C:/Users/user/go/pkg/mod/github.com/apache/thrift@v0.13.0/lib/go/thrift/socket.go:111
github.com/apache/thrift/lib/go/thrift.(*TSocket).Open(0x0, 0x10, 0x0)
	C:/Users/user/go/pkg/mod/github.com/apache/thrift@v0.13.0/lib/go/thrift/socket.go:85 +0x30
github.com/beltran/gohive.innerConnect(0x75c2a7, 0xa, 0x2710, 0x75aaff, 0x4, 0xc00010e000, 0x0, 0x1, 0x16)
	C:/Users/user/go/pkg/mod/github.com/beltran/gohive@v1.1.0/hive.go:165 +0x1c3
github.com/beltran/gohive.Connect(...)
	C:/Users/user/go/pkg/mod/github.com/beltran/gohive@v1.1.0/hive.go:118
main.main()
	c:/Users/user/go/src/value-mapping-service-hdfs-writer/main.go:16 +0x133
exit status 2

[Done] exited with code=1 in 1.314 seconds
```

It seems that "connection, errConn := gohive.Connect("localhost:", 10000, "NONE", configuration)" starts this issue and goes deeper.

I noticed that if using "localhost" instead of "localhost:", I get the error:
```
2020/05/08 14:32:56 Required field 'sessionId' is unset! Struct:TSessionHandle(sessionId:null)
exit status 1
```

I'm asking because I'm slightly confused how to connect to my locally hosted Hive. Any help is appreciated.

**Comment by beltran** [comment] 2020-05-08 15:29
Hello, you should definitely be using `localhost` instead of `localhost:`, that's what's causing the first stacktrace.

I'm not sure how you are getting the second error, can you share the code? I'd suggest tweaking [this line](https://github.com/beltran/gohive/blob/master/example/main.go#L16) and setting auth to `"NONE"`, you'll have to set the username and password as well:

```
configuration.Username = "myUsername"
configuration.Password = "myPassword"
``` 

There's some more info in [this section](https://github.com/beltran/gohive#connnect-using-plain-sasl) of the readme.

**Comment by KaluTheKova** [comment] 2020-05-11 05:48
Helloes,

curiously enough, I ran the exact same code today and it worked. Well, it connected to Hive, created the table but hung on insert. So, the following problem is with Hive itself and not with this code, which is good to know.

Here is the code I used:
```
package main

import (
	"context"
	"log"

	"github.com/beltran/gohive"
)

func main() {
	ctx := context.Background()
	configuration := gohive.NewConnectConfiguration()
	configuration.Service = "hive"
	configuration.FetchSize = 1000
	// Previously kinit shoulds have done: kinit -kt ./secret.keytab hive/hs2.example.com@EXAMPLE.COM
	connection, errConn := gohive.Connect("localhost", 10000, "NONE", configuration)
	if errConn != nil {
		log.Fatal("Error in gohive.Connect", errConn)
	}
	cursor := connection.Cursor()

	cursor.Exec(ctx, "CREATE TABLE myTable (a INT, b STRING)")
	if cursor.Err != nil {
		log.Fatal(cursor.Err)
	}

	cursor.Exec(ctx, "INSERT INTO myTable VALUES(1, '1'), (2, '2'), (3, '3'), (4, '4')")
	if cursor.Err != nil {
		log.Fatal(cursor.Err)
	}

	cursor.Exec(ctx, "SELECT * FROM myTable")
	if cursor.Err != nil {
		log.Fatal(cursor.Err)
	}

	var i int32
	var s string
	for cursor.HasMore(ctx) {
		if cursor.Err != nil {
			log.Fatal(cursor.Err)
		}
		cursor.FetchOne(ctx, &i, &s)
		if cursor.Err != nil {
			log.Fatal(cursor.Err)
		}
		log.Println(i, s)
	}

	cursor.Close()
	connection.Close()
}
```

**Comment by beltran** [comment] 2020-05-11 14:51
Hello, happy to hear, I'll close this since the issue is with hive and not the driver.

**Closed by beltran** 2020-05-11 14:51 UTC
